[package]
name = "cosmos"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1.20.1", features = ["full"] }
anyhow = "1.0.59"
tonic = { version = "0.7", features = ["channel", "tls", "tls-roots"], default-features = false }
cosmos-sdk-proto = { version = "0.13.0", features = ["cosmwasm"] }
prost = "0.10.4"
bech32 = "0.9.0"
bitcoin = "0.28.1"
hkd32 = { version = "0.7.0", features = ["bip39"] }
once_cell = "1.13.0"
rand = "0.8.5"
log = "0.4.17"
fs-err = "2.7.0"
serde = "1"
serde_json = "1"
chrono = "0.4"
hex = "0.4"
sha2 = "0.10"

[dev-dependencies]
quickcheck = "1"
